BADProject/BADProject.WebUI/Controllers/AnimeController.cs
using BADProject.Application.Services.Interfaces;
using BADProject.WebUI.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using BADProject.Domain.Entities;
using BADProject.Infrastructure.Repositories;
using Microsoft.AspNetCore.Identity;
using SportStore.Infrastructure.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace BADProject.WebUI.Controllers
{
    [Authorize(Policy = "CanManageCatalog")]
    public class AnimeController : Controller
    {
        private readonly IFileUploadService _fileUploadService;
        private readonly IAnimeService _animeService;
        private readonly UserManager<ApplicationUser> _userManager;

        public AnimeController(IFileUploadService fileUploadService, IAnimeService animeService, UserManager<ApplicationUser> userManger)
        {
            _fileUploadService = fileUploadService;
            _animeService = animeService;
            _userManager = userManger;
        }

        public async Task<IActionResult> AddAnime()
        {
            List<Genre> genresList = await _animeService.GetAllGenres(); 
            AnimeViewModel viewModel = new AnimeViewModel
            {
                GenresList = genresList
            };
            return View("AddAnime", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAnime(AnimeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.GenresList = await _animeService.GetAllGenres();
                return View("AddAnime", model);
            }
            if (model.Image != null && model.Image.Length > 0)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.Image.FileName);
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images", fileName);

                await _fileUploadService.UploadFile(model.Image.OpenReadStream(), filePath);

                model.ImageURL = fileName;
            }
            Anime animes = new Anime
            {
                Title = model.Title,
                Description = model.Description,
                Release_date = model.ReleaseDate,
                GenreId = model.GenreId,
                ImageURL = model.ImageURL
            };

            await _animeService.Toevoegen(animes);

            return RedirectToAction("AnimeList", "AnimeList");
        }

        [AllowAnonymous]
        public async Task<IActionResult> Review(int id)
        {
            Anime anime = await _animeService.FindByAnimeId(id);
            IEnumerable<Reviews> reviews = await _animeService.FindReviewByAnimeId(id);
            List<Genre> genresList = await _animeService.GetAllGenres();

            double averageRating = (double)(reviews.Any() ? reviews.Average(r => r.Rating) : 0);

            AnimeViewModel model = new AnimeViewModel
            {
                Id = anime.Id,
                Title = anime.Title,
                Description = anime.Description,
                ImageURL = anime.ImageURL,
                ReleaseDate = anime.Release_date,
                GenreName = anime.Genre.Name,
                Reviews = reviews.ToList(),
                AverageRating = (double)averageRating
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> AddReview(int animeId, int rating, string review)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Review", new { id = animeId });
            }

            string? userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
            {
                // Generate the return URL
                string returnUrl = Url.Action(nameof(AddReview), new { animeId = animeId, rating = rating, review = review });

                // Redirect to the login page with the return URL as a query parameter
                return RedirectToPage("/Account/Login", new { area = "Identity", ReturnUrl = returnUrl });
            }

            var user = await _userManager.FindByIdAsync(userId);
            Reviews newReview = new Reviews
            {
                Rating = rating,
                Review = review,
                AnimeId = animeId,
                UserId = userId,
                UserName = user.FirstName + "" + user.LastName, 
                DateTime = DateTime.Now
            };

            await _animeService.AddReview(newReview);
            return RedirectToAction("Review", new { id = animeId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> DeleteReview(int id, int animeId)
        {
            Reviews review = await _animeService.FindReviewById(id);
            if (review == null)
            {
                return RedirectToAction("Review", new { id = animeId });
            }

            string currentUserId = _userManager.GetUserId(User);
            if (review.UserId != currentUserId && !User.HasClaim("CanManageCatalog", "true"))
            {
                return Unauthorized();
            }

            await _animeService.DeleteReview(id);
            return RedirectToAction("Review", new { id = animeId });
        }


    }
}

BADProject/BADProject.WebUI/Controllers/AnimeListController.cs
using BADProject.Application.Services;
using BADProject.Application.Services.Interfaces;
using BADProject.Domain.Entities;
using BADProject.Infrastructure.Repositories;
using BADProject.WebUI.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SportStore.Infrastructure.Identity;
using System.Collections.Generic;

namespace BADProject.WebUI.Controllers
{
    public class AnimeListController : Controller
    {
        private readonly IFileUploadService _fileUploadService;
        private readonly IAnimeService _animeService;
        private readonly IAnimeListService _animeListService;
        private readonly UserManager<ApplicationUser> _userManager;
        public AnimeListController(IFileUploadService fileUploadService, IAnimeService animeService, IAnimeListService animeListService, UserManager<ApplicationUser> userManager)
        {
            _fileUploadService = fileUploadService;
            _animeService = animeService;
            _animeListService = animeListService;
            _userManager = userManager;
        }

        public async Task<IActionResult> AnimeList()
        {
            var userId = _userManager.GetUserId(User);

            List<Anime> animes = await _animeService.GetAllAnime();
            List<AnimeViewModel> viewModelList = new List<AnimeViewModel>();

            foreach (Anime anime in animes)
            {
                bool isInWatchList = await _animeListService.IsAnimeInWatchList(anime.Id, userId);  

                IEnumerable<Reviews> reviews = await _animeService.FindReviewByAnimeId(anime.Id);
                double averageRating = reviews.Any() ? reviews.Average(r => r.Rating) : 0;

                AnimeViewModel viewModel = new AnimeViewModel
                {
                    Id = anime.Id,
                    Title = anime.Title,
                    Description = anime.Description,
                    ImageURL = anime.ImageURL,
                    GenreName = anime.Genre.Name,
                    AverageRating = averageRating,
                    IsInWatchList = isInWatchList
                };
                viewModelList.Add(viewModel);
            }
            return View(viewModelList);
        }

        [Authorize(Policy = "CanManageCatalog")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            _animeListService.DeleteProduct(id);
            return RedirectToAction("AnimeList", "AnimeList");
        }
        public async Task<IActionResult> Edit(int id)
        {
            Anime anime = await _animeListService.FindById(id);

            AnimeViewModel viewModel = new AnimeViewModel
            {
                Id = anime.Id,
                Title = anime.Title,
                Description = anime.Description,
                ReleaseDate = anime.Release_date,
                GenreId = anime.GenreId,
                ImageURL = anime.ImageURL,
                GenresList = await _animeService.GetAllGenres()
            };

            return View(viewModel);
        }

        [Authorize(Policy = "CanManageCatalog")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AnimeViewModel model)
        {

            if (model.Image == null || model.Image.Length == 0)
            {
                ModelState.Remove("Image");
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Anime anime = await _animeListService.FindById(id);
            if (anime == null)
            {
                return NotFound();
            }

            if (model.Image != null && model.Image.Length > 0)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.Image.FileName);
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images", fileName);

                await _fileUploadService.UploadFile(model.Image.OpenReadStream(), filePath);
                anime.ImageURL = fileName;
            }

            anime.Title = model.Title;
            anime.Description = model.Description;
            anime.Release_date = model.ReleaseDate;
            anime.GenreId = model.GenreId;

            await _animeListService.UpdateAnime(anime);

            return RedirectToAction("AnimeList", "AnimeList");
        }

        public async Task<IActionResult> WatchLists()
        {
            string? userId = _userManager.GetUserId(User);
            IEnumerable<Anime> watchlistAnimes = await _animeListService.GetWatchListByUserId(userId);
            return View("WatchList", watchlistAnimes);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToWatchList(int id) 
        {
            string? userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }
            if (!await _animeListService.IsAnimeInWatchList(id, userId))
            {
                await _animeListService.AddToWatchList(id, userId);
            }

            return RedirectToAction("WatchLists");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveFromWatchList(int id)
        {
            string? userId = _userManager.GetUserId(User);
            await _animeListService.RemoveFromWatchList(id, userId);
            return RedirectToAction("WatchLists");
        }
    }
}

BADProject/BADProject.WebUI/Views/AnimeList/AnimeList.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@using BADProject.Domain.Entities
@model List<BADProject.WebUI.Models.ViewModels.AnimeViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "All Anime";
}
<h1>All Anime</h1>


<div class="container mt-3">
    <div class="row">
        <div class="col-12 mb-3">
            @if ((await AuthorizationService.AuthorizeAsync(User, null, "CanManageCatalog")).Succeeded)
            {
                <a asp-controller="Anime" asp-action="AddAnime" class="btn btn-success">
                    <i class="fas fa-plus"></i> Add New Anime
                </a>
            }
        </div>
    </div>
</div>
<div class="container mt-2">
    <div class="row">
        @foreach (var anime in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card anime-card">
                    <img src="@Url.Content("~/Images/" + anime.ImageURL)" alt="Image for @anime.Title" class="card-img-top">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <h2 class="card-title">@anime.Title</h2>
                            <form asp-controller="AnimeList" asp-action="AddToWatchList" method="post">
                                <input type="hidden" name="id" value="@anime.Id" />
                                <button type="submit" style="background: transparent; border: none;">
                                    <i class="fas fa-heart" style="color: @(anime.IsInWatchList ? "#ff0000" : "#808080");"></i>
                                </button>
                            </form>

                        </div>
                        <p class="card-text">@anime.Description</p>
                        <p class="genre"><strong>Genre:</strong> @anime.GenreName</p>
                        <div class="icons-container d-flex align-items-center">
                            <a asp-controller="Anime" asp-action="Review" asp-route-id="@anime.Id" style="text-decoration: none;">
                                <div class="star-rating">
                                    @for (int i = 1; i <= 5; i++)
                                    {
                                        <span class="star" style="color: @(i <= Math.Ceiling(anime.AverageRating) ? "gold" : "gray");">&#9733;</span>
                                    }
                                </div>
                            </a>
                            <div class="management-buttons mt-2">
                                @if ((await AuthorizationService.AuthorizeAsync(User, null, "CanManageCatalog")).Succeeded)
                                {
                                    <a asp-controller="AnimeList" asp-action="Edit" asp-route-id="@anime.Id" class="btn btn-primary"><i class="fas fa-edit"></i></a>
                                    <form asp-controller="AnimeList" asp-action="Delete" method="post" style="display: inline;">
                                        <input type="hidden" name="id" value="@anime.Id" />
                                        <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                    </form>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

BADProject/BADProject.WebUI/Views/AnimeList/Edit.cshtml
@model BADProject.WebUI.Models.ViewModels.AnimeViewModel
@{
    ViewData["Title"] = "Add Anime";
}
@using BADProject.Domain.Entities
<h1>Add Anime</h1>

<form asp-controller="AnimeList" asp-action="Edit" method="post" enctype="multipart/form-data">
    <input type="hidden" name="id" value="@Model.Id" />
    <div class="form-group mb-3">
        <label asp-for="Title">Title:</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Description">Description:</label>
        <textarea asp-for="Description" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="ReleaseDate">Release Date:</label>
        <input type="date" asp-for="ReleaseDate" class="form-control" />
        <span asp-validation-for="ReleaseDate" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="GenreId">Genre:</label>
        <select asp-for="GenreId" class="form-control">
            <option value="">-- Select Genre --</option>
            @foreach (Genre genres in Model.GenresList)
            {
                <option value="@genres.Id">@genres.Name</option>
            }
        </select>
        <span asp-validation-for="GenreId" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Image">Image:</label><br />
        <input type="file" asp-for="Image" class="form-control" data-val="false"/>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BADProject/BADProject.WebUI/Views/AnimeList/WatchList.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@using BADProject.Domain.Entities
@model List<Anime>

@{
    ViewData["Title"] = "My Watch List";
}

<h1>@ViewData["Title"]</h1>

<div class="container mt-3">
    <div class="row">
        @foreach (var anime in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card anime-card">
                    <img src="@Url.Content("~/Images/" + anime.ImageURL)" alt="Image for @anime.Title" class="card-img-top">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <h5 class="card-title">@anime.Title</h5>
                                <form asp-action="RemoveFromWatchList" asp-controller="AnimeList" asp-route-id="@anime.Id" method="post">
                                    <button type="submit" class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                        </div>
                        <p class="card-text">@anime.Description</p>
                        <a asp-controller="Anime" asp-action="Review" asp-route-id="@anime.Id">Check the reviews!</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>